name: Selenium Hybrid Framework CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Start Juice Shop with Docker
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
          # Wait for the application to be ready
          for i in {1..20}; do
            nc -z localhost 3000 && break
            sleep 2
          done

      - name: Run Automated Tests
        # 'mvn clean test' purani reports delete karke fresh run karega
        run: mvn clean test

      - name: Upload Test Artifacts
        # 'if: always()' ensures ki pass ho ya fail, reports hamesha upload hon
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-reports-and-screenshots
          # Aapke project ke folders ka path (Case-sensitive for Linux)
          path: |
            screenshots/
            test-output/
            reports/
          retention-days: 5 # 5 din baad automatically delete ho jayega space bachane ke liye
